User's Guide
------------

This part of the documentation, mostly consisting of prose, begins
with background information of Mailthon, and focuses on getting
started with the library.

.. toctree::
   :maxdepth: 2
   
   foreword
   installation
   quickstart
   indepth

Developer Reference
-------------------

If you are looking for specific classes, methods or functions,
or curious about why certain things work the way they work, this
part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api
   design
