User's Guide
------------

This part of the documentation, mostly consisting of prose, begins
with background information of Mailthon, and focuses on getting
started with the library.

.. toctree::
   :maxdepth: 2
   
   foreword
   installation
   quickstart

API Reference
-------------

If you are looking for specific classes, methods or functions,
this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api
